### ISSUE TITLE
Bug: Hover over the open contextmenu button

### ISSUE THREAD

**Issue by KominoStyle** [zanllp/sd-webui-infinite-image-browsing#180]
After hovering over the button, I noticed that the image-Information can't be folded.

![Image 1](https://puu.sh/JHpLq/e1862ff7cf.png)

![Image 2](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/91426727/d3013a73-3eb3-4109-94cb-908b8c854836)

In addition, an error log is displayed in the console, which might be the reason why the image-Information doesn't change when navigating to the next image. Here is the error message:

```
index-a67778ed.js:1 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at insert (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:55943)
    at b (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:38657)
    at m (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:38280)
    at k (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:40850)
    at I (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:40196)
    at S (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:38982)
    at m (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:38381)
    at Vu.te [as fn] (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:42269)
    at Vu.run (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:5680)
    at R.P.update (http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-a67778ed.js:1:42986)
```

**Comment by zanllp** [comment]
Already fixed
