### ISSUE TITLE
No module named 'functional' in iib/api.py error

### ISSUE THREAD

**Issue by Chubbly** [zanllp/sd-webui-infinite-image-browsing#336]
I've just updated to latest version and when I try to start infinite browser, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\hoffl\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\app.py", line 6, in <module>
    from scripts.iib.api import infinite_image_browsing_api, index_html_path
  File "C:\Users\hoffl\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\iib\api.py", line 45, in <module>
    from functional import seq
ModuleNotFoundError: No module named 'functional'
```

The extension won't start now.

**Comment by zanllp** [comment]
This is a new dependency. If it is launched as an extension of sd-webui, it will be installed automatically. If it is launched in standalone mode, you will need to install it manually by running `pip install -r requirements.txt`.

**Comment by Chubbly** [comment]
That fixed it, thank you!
