### ISSUE TITLE
BROWSER CAN'T START WITH SECOND COLAB RUN

### ISSUE THREAD

**Issue by zx3on** [zanllp/sd-webui-infinite-image-browsing#374]
EVERYTHING WORKS FINE UNTIL I BACK TO COLAB NEXT DAY AND WANT TO RUN IT, EVERY TIME WHEN I REINSTAL WEBUI INFINITY BROWSER IT CAN'T START ON NEXT NEW START OF COLAB NOTEBOOK.

No module named 'dotenv'
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 50, in <module>
        from functional import seq
    ModuleNotFoundError: No module named 'functional'

**Comment by zanllp** [comment]
`pip install -r requirements.txt`

**Comment by zanllp** [comment]
You can try restarting sd-webui or manually installing the dependencies to see if that helps.

**Comment by zx3on** [comment]
It did't help at all.

**Comment by Yuhyeong** [comment]
the same problem at my own linux server

**Comment by turtleturtle92** [comment]
Same problem. After manually installing `functional`, throws error `ImportError: cannot import name 'seq' from 'functional'`. 

```
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/workspace/sd/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 50, in <module>
        from functional import seq
    ImportError: cannot import name 'seq' from 'functional' (/usr/local/lib/python3.10/dist-packages/functional/__init__.py)
```

**Comment by zanllp** [comment]
What version of SDWebUI are you running on? I have been unable to reproduce this issue.

**Comment by zanllp** [comment]
> Same problem. After manually installing `functional`, throws error `ImportError: cannot import name 'seq' from 'functional'`.
> 
> ```
> *** Error loading script: iib_setup.py
>     Traceback (most recent call last):
>       File "/workspace/sd/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "/workspace/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
>         from scripts.iib.api import infinite_image_browsing_api, send_img_path
>       File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 50, in <module>
>         from functional import seq
>     ImportError: cannot import name 'seq' from 'functional' (/usr/local/lib/python3.10/dist-packages/functional/__init__.py)
> ```
It's not 'functional,' it's 'pyfunctional.' Please refer to this link: https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/requirements.txt.

**Comment by turtleturtle92** [comment]
> It's not 'functional,' it's 'pyfunctional' Please refer to this link: https://github.com/zanllp/sd-webui-infinite-image-browsing/blob/main/requirements.txt.

My SDWebUI is not current but this fixed my problem. Thanks!

**Comment by rchennau** [comment]
Same issue.  I had to install manually install pyfunctional with python -m pip install pyfunctional.
requirements.txt listed it but it
