### ISSUE TITLE
infinite-image-browsing listen 0.0.0.0? (standalone ubuntu)

### ISSUE THREAD

**Issue by freke70** [zanllp/sd-webui-infinite-image-browsing#391]
Is there a way to set it to listen on 0.0.0.0 and choose the port?
Unfortunately, localhost is not very interesting when using cloud computing.

Thanks for taking a look.

**Comment by zanllp** [comment]
```bash
python app.py --host="0.0.0.0" --port=8888
```

![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/25872019/d6a1aa93-2a14-41ca-b743-66ca90200f03)

**Comment by freke70** [comment]
Thanks for the swift reply.
I installed the deb file, so I figured I needed to start it with "infinite-image-browsing"

Using the git, I get this error:

`sudo python3 app.py --host="0.0.0.0" --port=8888
Traceback (most recent call last):
  File "/tmp/sd-webui-infinite-image-browsing/app.py", line 221, in <module>
    launch_app(**vars(args))
  File "/tmp/sd-webui-infinite-image-browsing/app.py", line 201, in launch_app
    app = app_utils.get_root_browser_app()
  File "/tmp/sd-webui-infinite-image-browsing/app.py", line 142, in get_root_browser_app
    self.wrap_app(app)
  File "/tmp/sd-webui-infinite-image-browsing/app.py", line 121, in wrap_app
    infinite_image_browsing_api(
  File "/tmp/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 597, in infinite_image_browsing_api
    class MatchImagesByTagsReq(BaseModel):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 352, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `size = 200`. All model fields require a type annotation; if `size` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.3/u/model-field-missing-annotation
`

I'm using comfyui, so no A1111 or anything like that.

**Comment by zanllp** [comment]
Try updating to the latest version and see if this problem is resolved.

**Comment by freke70** [comment]
Thanks, that fixed it.
Thanks for your very prompt and speedy response!
