### ISSUE TITLE
[Bug] ImportError: cannot import name 'seq' from 'functional' (unknown location)

### ISSUE THREAD

**Issue by mizukarada** [zanllp/sd-webui-infinite-image-browsing#396]
Got this error:
```shell
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "C:\Users\anon\Downloads\Programs\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\anon\Downloads\Programs\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\anon\Downloads\Programs\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "C:\Users\anon\Downloads\Programs\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\iib\api.py", line 51, in <module>
        from functional import seq
    ImportError: cannot import name 'seq' from 'functional' (unknown location)
```
Changing it to `from functional.streams import seq` solves the issue.

**Comment by duanjiding** [comment]
same issue

**Comment by erginbilgin** [comment]
I'm experiencing this issue as well. Workaround above is not helping in my case either.

**Comment by tedited78** [comment]
I confirm - change to functional.streams only throws:

File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 54, in <module>
        from functional.streams import seq
    ModuleNotFoundError: No module named 'functional.streams'

**Comment by long369486562** [comment]
> I confirm - change to functional.streams only throws:
> 
> File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 54, in from functional.streams import seq ModuleNotFoundError: No module named 'functional.streams'

me too

**Comment by zanllp** [comment]
@tedited78 @long369486562 Update IIB (this extension) to the latest version to fix this issue
