### ISSUE TITLE
Tab Not Displaying

### ISSUE THREAD

**Issue by saltyollpheist** [zanllp/sd-webui-infinite-image-browsing#411]
**Description**
Tab doesn't display and thus cannot be used.

**To Reproduce**
1. Go to Extensions tab then Available sub-tab. 
2. Click 'Load From' using default parameters.
3. Scroll and locate 'sd-webui-infinite-image-browsing' and click Install. 
4. Software is installed and even updating when prompted to do so. UI and entire SD host has been restarted multiple times. Issue persists. 

**Expected behavior**
I expect the tab to show after installation has completed. 

**Additional context**
Using version [09767d96](https://github.com/zanllp/sd-webui-infinite-image-browsing/commit/09767d969964b1379a9048dcec524c832a239177). 
OS is AlmaLinux 9.2. 
Any additional context I can provide to be helpful, please, let me know. Thanks.

**Comment by zanllp** [comment]
I was unable to reproduce this issue on WSL Ubuntu. Did your terminal display any other error messages?

**Comment by saltyollpheist** [comment]
> I was unable to reproduce this issue on WSL Ubuntu. Did your terminal display any other error messages?

Pasting below what generates as soon as I launch Stable Diffusion. `sd-civitai-browser-plus` works fine along with `sd-dynamic-prompts`, and `sd_delete_button`. However, it seems from the error messages, `sd-masonry`, your plug-in, and `sd-webui-fabric` are not loading appropriately. Could this be a permissions or pathing issue? I'm still a novice when it comes to Python. I tried the workarounds mentioned in this [thread](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150) from the FAQ, but still no resolution. Many thanks for your assistance and the quick response. 

```
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/extensions/sd-masonry/scripts/main.py", line 3, in <module>
        import sqlite3
      File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ModuleNotFoundError: No module named '_sqlite3'

---
Loading FABRIC v0.6.1
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/run/media/alleck/_ext240gb/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 4, in <module>
        import sqlite3
      File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by zanllp** [comment]
It seems that your Python runtime environment is incomplete and lacks SQLite. You can install a complete Python setup to resolve this issue, for example, using tools like pyenv. I'm not very familiar with the specifics since I haven't used this system myself, but you can reach out to relevant members of the community for assistance. This issue is not a bug in the plugin itself.

**Comment by saltyollpheist** [comment]
@zanllp That's excellent news and at least gives me a great jumping off point for a resolution. I'll keep poking at it and see if I can't implement that accordingly. Thank you much for the direction, and I'll go ahead and close this as resolved. 

Cheers.

**Comment by saltyollpheist** [comment]
Just wanted to add for anyone who stumbles across this thread with a similar issue, the tried and true method of full reinstall resolved the issue. 

That's what I get for performing an install and then moving the folder to a different directory. If you who are reading this are experiencing the above issue and have done what I did, simply reinstall the base installation with a newly established Python venv. Then you can simply drag and drop all your modules, embeddings, plug-ins, etc. to your new installation, restart the script for the web UI, and you're good to go.
