### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by dmnwuguo** [zanllp/sd-webui-infinite-image-browsing#435]
### version:
python 3.10.6
Stable diffusion webui 1.6

### error info:

*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/data/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/data/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/data/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/data/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 4, in <module>
        import sqlite3
      File "/usr/local/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ModuleNotFoundError: No module named '_sqlite3'

**Comment by zanllp** [comment]
https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/411
