### ISSUE TITLE
安装sd-webui-infinite-image-browsing之后，无法打开fastapi网页，报错KeyError: <class 'scripts.iib.api.infinite_image_browsing_api.<locals>.MoveFilesReq'>

### ISSUE THREAD

**Issue by jaycecd** [zanllp/sd-webui-infinite-image-browsing#450]
感谢作者出色的工作，很好用！但目前遇到一个问题：安装sd-webui-infinite-image-browsing之后，fastapi网页没法打开了，报错`KeyError: <class 'scripts.iib.api.infinite_image_browsing_api.<locals>.MoveFilesReq'>`：

`*** API error: GET: http://127.0.0.1:7860/openapi.json {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "<class 'scripts.iib.api.infinite_image_browsing_api.<locals>.MoveFilesReq'>"}
    Traceback (most recent call last):
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Code\Python\Git\stable-diffusion-webui\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "E:\Code\Python\Git\stable-diffusion-webui\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
        await self.app(scope, receive, send)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
        raise e
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
        await self.app(scope, receive, send)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 247, in openapi
        return JSONResponse(self.openapi())
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 219, in openapi
        self.openapi_schema = get_openapi(
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\openapi\utils.py", line 475, in get_openapi
        field_mapping, definitions = get_definitions(
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\_compat.py", line 471, in get_definitions
        return {}, get_model_definitions(
      File "E:\Code\Python\Git\stable-diffusion-webui\venv\lib\site-packages\fastapi\_compat.py", line 374, in get_model_definitions
        model_name = model_name_map[model]
    KeyError: <class 'scripts.iib.api.infinite_image_browsing_api.<locals>.MoveFilesReq'>`

网页端（http://127.0.0.1:7860/docs）显示：
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/33342388/dbdb93ad-c7b1-41f5-9ada-a79364774324)
而我将sd-webui-infinite-image-browsing删除之后，fastapi网页能正常打开：
![image](https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/33342388/0a89f7a3-57b9-42c3-bc01-a4bdda357b74)
原来的fastapi版本是0.94.0，怀疑是版本问题，已经更新到0.103.2版本，但依然报错，该怎么解决呢？

**Comment by zanllp** [comment]
我是0.95.2，是正常的，不过我感觉可能是其他原因，后面有时间再看
