### ISSUE TITLE
Rebuild Image Index - Ends in Error

### ISSUE THREAD

**Issue by Manniala** [zanllp/sd-webui-infinite-image-browsing#467]
Hey, it is probably not a coding error, but more likely a database error (i think).
I ran a Rebuild the other day and it had no error, i ran it again today and it let to the error below.

I was hoping you could tell me how to safely restore the database, if it is a database error that is.

`*** API error: POST: http://127.0.0.1:7861/infinite_image_browsing/db/rebuild_index {'error': 'IntegrityError', 'detail': '', 'body': '', 'errors': 'UNIQUE constraint failed: image_tag.image_id, image_tag.tag_id'}
    Traceback (most recent call last):
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
        return await dependant.call(**values)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\api.py", line 827, in rebuild_index
        rebuild_image_index(search_dirs = get_img_search_dirs() + mem["extra_paths"])
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 151, in rebuild_image_index
        update_image_data(search_dirs=search_dirs, is_rebuild=True)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 131, in update_image_data
        process_folder(dir)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 62, in process_folder
        process_folder(file_path)
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 102, in process_folder
        safe_save_img_tag(ImageTag(img.id, size_tag.id))
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\update_image_data.py", line 51, in safe_save_img_tag
        img_tag.save(conn)  # \u539f\u5148\u7528\u6765\u5904\u7406\u4e00\u4e9b\u610f\u5916\uff0c\u4f46\u662f\u5199\u7684\u6b63\u786e\u5b8c\u5168\u6ca1\u95ee\u9898,\u53bb\u6389\u4e86try catch
      File "F:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-infinite-image-browsing\scripts\iib\db\datamodel.py", line 339, in save
        cur.execute(
    sqlite3.IntegrityError: UNIQUE constraint failed: image_tag.image_id, image_tag.tag_id`

**Comment by zanllp** [comment]
Try rebuilding the index again.

**Comment by Manniala** [comment]
Hey, i have done that several times, but always ends with the same error, but it does look like that the database still works, i can add new tags... so not sure what the error means, when every thing seems to work.

**Comment by zanllp** [comment]
This type of error could potentially result in some tags missing. I haven't been able to reproduce this error yet, so I don't know what is causing it. However, I can try to temporarily resolve this issue.

**Comment by zanllp** [comment]
you can update to the latest version and try again.

**Comment by Manniala** [comment]
Hey again, and "Rebuild complete" 👍 there are no errors, coffee inc :)
