### ISSUE TITLE
DB error (Image search)

### ISSUE THREAD

**Issue by bluenyx** [zanllp/sd-webui-infinite-image-browsing#52]
![image](https://user-images.githubusercontent.com/96876/234461063-f46d851a-5d30-4618-830c-1400a8db0575.png)

Error when pressing Image Search. No logs were left, so it's not clear what the error was. After the first time it works, it happens when you click Reload UI. After that, it doesn't work.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\api.py", line 349, in match_image_by_tags
    ids = [int(x) for x in tag_ids.split(',')]
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\api.py", line 349, in <listcomp>
    ids = [int(x) for x in tag_ids.split(',')]
ValueError: invalid literal for int() with base 10: ''

  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\api.py", line 328, in get_db_basic_info
    img_count = DbImg.count(conn)
  File "C:\Users\bluen\Documents\AI\stable-diffusion-webui\extensions\sd-webui-infinite-image-browsing\scripts\db\datamodel.py", line 106, in count
    with closing(conn.cursor()) as cur:
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 11760 and this is thread id 25828.

**Comment by zanllp** [comment]
You need to select a tag first before clicking the search button. 

You can select a tag by clicking on the tags listed below or by manually typing a tag in the input box. 

I forgot to add a restriction for this case.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/25872019/234471429-aa6d407f-cdb0-4f69-809c-4e292fd4d09d.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/25872019/234471448-7c7d6882-25be-454f-b5a6-5b3f888de120.png">

**Comment by bluenyx** [comment]
What about images without tags?

**Comment by bluenyx** [comment]
![image](https://user-images.githubusercontent.com/96876/234480278-00b1a298-1c50-4fee-97df-f07487a945dd.png)
![image](https://user-images.githubusercontent.com/96876/234480312-2fe17b5a-3656-4989-8996-bdc72a929272.png)
![image](https://user-images.githubusercontent.com/96876/234480325-54613e49-5e93-40f8-8f2d-002954054e04.png)

And it doesn't search for anything with tags.

**Comment by zanllp** [comment]
Why are there no tags when using images generated by stable-diffusion-webui?

 If you can see the image generation information through the right-click menu, there must be relevant tags.

 For example, your model, size, sampler, positive prompt, Lora, and so on will be automatically converted into tags.

**Comment by zanllp** [comment]
Are you run this repo separately   and no pass *--sd_webui_config* param?

<img width="907" alt="image" src="https://user-images.githubusercontent.com/25872019/234481902-fdd79947-237a-44c9-ba28-f2033fe0dc9f.png">

**Comment by bluenyx** [comment]
> Did you run this repo separately without passing the --sd_webui_config parameter?
> 
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/25872019/234481902-fdd79947-237a-44c9-ba28-f2033fe0dc9f.png">

yes

**Comment by bluenyx** [comment]
> Why are there no tags when using images generated by stable-diffusion-webui?
> 
> If you can see the image generation information through the right-click menu, there must be relevant tags.
> 
> For example, your model, size, sampler, positive prompt, Lora, and so on will be automatically converted into tags.

The ones with and without tags are together.

**Comment by bluenyx** [comment]
The image you uploaded is tagged "1girl". However, when hit Search, I don't see anything.

**Comment by zanllp** [comment]
> The image you uploaded is tagged "1girl" and ETC.. . However, when hit Search, I don't see anything.
> 
> ![image](https://user-images.githubusercontent.com/96876/234491718-bde70608-93af-4d13-abd5-6a3b9d9cd826.png)
> 
> ![image](https://user-images.githubusercontent.com/96876/234492127-7dcdf1fb-b253-4d36-b4da-3c773cef10e5.png)

Suddenly found.
It seems that your --sd_webui_config parameter is referring to a directory, rather than a JSON file. 
This is the path to my JSON config file: C:\Users\zanllp\Desktop\stable-diffusion-webui\config.json.

this file, In  sd-webui working directory 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/25872019/234672340-03c294d0-a013-4b92-9e83-b3d6a977d6a5.png">

**Comment by bluenyx** [comment]
![image](https://user-images.githubusercontent.com/96876/234736520-502a90e9-6b5a-4a9e-a846-54127fa1a75c.png)
![image](https://user-images.githubusercontent.com/96876/234736676-1556a452-35ad-46b0-bf37-9f65287373dc.png)
![image](https://user-images.githubusercontent.com/96876/234736741-fbd77cd9-1195-457a-886e-2a56fa7ee72f.png)

Did I run it the wrong way?

**Comment by zanllp** [comment]
Now it looks like the parameters are correct.
 Did clicking 'generate image for image index' still fail to generate the tag? If it still doesn't work, could you pull the repository and try running it again?

**Comment by zanllp** [comment]
> ![image](https://user-images.githubusercontent.com/96876/234736520-502a90e9-6b5a-4a9e-a846-54127fa1a75c.png) ![image](https://user-images.githubusercontent.com/96876/234736676-1556a452-35ad-46b0-bf37-9f65287373dc.png) ![image](https://user-images.githubusercontent.com/96876/234736741-fbd77cd9-1195-457a-886e-2a56fa7ee72f.png)
> 
> Did I run it the wrong way?

You seem to have missed the step of installing dependencies, haven't you?

**Comment by bluenyx** [comment]
> > ![image](https://user-images.githubusercontent.com/96876/234736520-502a90e9-6b5a-4a9e-a846-54127fa1a75c.png) ![image](https://user-images.githubusercontent.com/96876/234736676-1556a452-35ad-46b0-bf37-9f65287373dc.png) ![image](https://user-images.githubusercontent.com/96876/234736741-fbd77cd9-1195-457a-886e-2a56fa7ee72f.png)
> > Did I run it the wrong way?
> 
> You seem to have missed the step of installing dependencies, haven't you?

I already have the requirement.txt installed. The add-on works very well. However, stand alone is still the same.

![image](https://user-images.githubusercontent.com/96876/234779687-99612c78-3e3c-4def-8b25-69951b054606.png)

**Comment by zanllp** [comment]
The UI in dark mode seems to have some issues too. I forgot to check it yesterday.
You can enable the development mode using `set APP_ENV=dev && python app.py [extra args]`. 
Errors will be written to the `log.log` file in the repo root directory. 
Please show me the error part of the log afterwards.

**Comment by bluenyx** [comment]
This is the log content before using git pull.
After using git pull, there is no log left.

2023-04-27 10:32:19,083 - scripts.logger - ERROR - [WinError 3] ������ ��θ� ã�� �� �����ϴ�: 'C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/stable-diffusion-webui-ux/outputs'
2023-04-27 10:32:22,759 - scripts.logger - ERROR - [WinError 3] ������ ��θ� ã�� �� �����ϴ�: 'C:/Users/bluen/Documents/AI/stable-diffusion-webui-ux/stable-diffusion-webui-ux/outputs'
