### ISSUE TITLE
help me,pls

### ISSUE THREAD

**Issue by xlibfly** [zanllp/sd-webui-infinite-image-browsing#568]
*** API error: GET: http://127.0.0.1:7860/infinite_image_browsing/fe-static/assets/index-423bec18.js {'error': 'FileNotFoundError', 'detail': '', 'body': '', 'errors': "[Errno 2] No such file or directory: 'D:\\\\sd-webui-aki-v4.5\\\\extensions\\\\sd-webui-infinite-image-browsing/vue/dist/assets/index-423bec18.js'"}
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\streams\memory.py", line 94, in receive
        return self.receive_nowait()
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\streams\memory.py", line 114, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\api\api.py", line 186, in exception_handling
        return await call_next(request)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 157, in _create_span_call
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\sd-webui-aki-v4.5\modules\api\api.py", line 150, in log_and_time
        res: Response = await call_next(req)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 157, in _create_span_call
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 157, in _create_span_call
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 256, in _sentry_exceptionmiddleware_call
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 157, in _create_span_call
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "<enhanced_experience vendors.sentry_sdk.integrations.starlette>", line 157, in _create_span_call
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "<enhanced_experience vendors.sentry_sdk.integrations.fastapi>", line 136, in _sentry_app
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\sd-webui-aki-v4.5\python\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
        return await dependant.call(**values)
      File "D:\sd-webui-aki-v4.5\extensions\sd-webui-infinite-image-browsing\scripts\iib\api.py", line 614, in serve_static_file
        with open(file_full_path, "r", encoding="utf-8") as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\sd-webui-aki-v4.5\\extensions\\sd-webui-infinite-image-browsing/vue/dist/assets/index-423bec18.js'

---

**Comment by zanllp** [comment]
Update to the latest IIB and then restart the launcher.
