### ISSUE TITLE
Structured Data not parsed correctly if model hash is added to infotext

### ISSUE THREAD

**Issue by voyageur** [zanllp/sd-webui-infinite-image-browsing#595]
Tested with sd-webui-infinite-image-browsing at a1279c24dd79085cbefae96a829f06c38b95600a (current main HEAD).

In my settings I have "Add model hash to infotext" and similar options enabled (can be found looking for "hash" in settings).
With that, the Structured Data infobox is blank (Source Text tab is working fine), with JS errors like:
```
index-1dba0a34.js:1 TypeError: Cannot create property 'model' on string '{&quot;lora:falloutpostsdxl&quot;: &quot;661870bee1&quot;, &quot;model&quot;: &quot;07b985d12f&quot;}'
    at dX (index-1dba0a34.js:197:438)
    at fp.fn (MultiSelectKeep-e434457c.js:2:13)
    at fp.run (index-1dba0a34.js:1:4919)
    at get value (index-1dba0a34.js:1:13688)
    at MultiSelectKeep-e434457c.js:2:5171
    at Object.r [as default] (index-1dba0a34.js:1:16794)
    at Proxy.<anonymous> (index-1dba0a34.js:93:65982)
    at bc (index-1dba0a34.js:1:17106)
    at fp.ae [as fn] (index-1dba0a34.js:1:42359)
    at fp.run (index-1dba0a34.js:1:4919)
gO @ index-1dba0a34.js:1
```

Here is a sample prompt causing this:
```
text "No Cousin Stuff!", movie poster of a man and woman kissing, falloutpostsdxl,<lora:falloutpostsdxl:0.8>, 1960s \(style\), blue jumpsuit,
Negative prompt: bad art, low quality, deformed, disfigured,  ugly, photo, cg, 3d, watermark , signature, repeating letters, malformed letters, doubles, inaccuracy, duplicate, warped text, extra limbs, floating limbs,
Steps: 40, Sampler: DPM++ 2M, Schedule type: Karras, CFG scale: 7.5, Seed: 2069035482, Size: 768x1280, Model hash: 07b985d12f, Model: SDXLFaetastic_v24, Lora hashes: "falloutpostsdxl: e2b147c9c4d1", Refiner: sd_xl_refiner_1.0_0.9vae, Refiner switch at: 0.8, Version: v1.9.0-15-gff6f4680, Hashes: {"lora:falloutpostsdxl": "661870bee1", "model": "07b985d12f"}, Source Identifier: Stable Diffusion web UI
```

Disabling the option, structured data is shown correctly
(note this settings is enabled by default in stable-diffusion-webui - add_model_hash_to_info)

**Comment by zanllp** [comment]
Already fixed
