### ISSUE TITLE
[问题反馈] 有的时候无法点开图片查看大图

### ISSUE THREAD

**Issue by lihaoyun6** [zanllp/sd-webui-infinite-image-browsing#70]
点开某个输出文件夹后预览正常显示, 但点击其中任何图片都打不开, 控制台报错如下(此现象会随机出现):  
```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/responses.py", line 342, in __call__
    raise RuntimeError(f"File at path {self.path} is not a file.")
RuntimeError: File at path /mnt/Data/sd-linux/outputs/txt2img-images/2023-05-02 is not a file.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/Data/sd-linux/extensions/sd-webui-infinite-image-browsing/scripts/api.py", line 313, in image_geninfo
    with Image.open(path) as img:
  File "/mnt/Data/sd-linux/venv/lib/python3.10/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
```

**Comment by lihaoyun6** [comment]
出现这种情况后, 点击"刷新"可以暂时解决. 但下次不知道什么时候又会发生

**Comment by zanllp** [comment]
这个报错是一直都有，但是没什么影响所以我一直没修 https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/35 
我感觉是其他原因 能不能看到前端的错误信息 ，就是控制台这，
<img width="656" alt="image" src="https://user-images.githubusercontent.com/25872019/235741935-94b28f7f-1a2b-42ca-a49c-d283bbf12461.png">
网络能看到最好，如果错误有个变红
<img width="708" alt="image" src="https://user-images.githubusercontent.com/25872019/235742164-362760dd-636e-4b9b-829c-38bf6d822167.png">

**Comment by lihaoyun6** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/16348097/235744816-86cf9b5c-479d-4564-ac55-e095b32a4b22.png">
在使用路径导航器返回上层目录后, 好像脚本会错误的把某个日期文件夹当做文件去尝试打开, 导致出现此错误

**Comment by zanllp** [comment]
> <img alt="image" width="563" src="https://user-images.githubusercontent.com/16348097/235744816-86cf9b5c-479d-4564-ac55-e095b32a4b22.png">
> 在使用路径导航器返回上层目录后, 好像脚本会错误的把某个日期文件夹当做文件去尝试打开, 导致出现此错误

这个问题你可以忽略，除了打印错误没什么影响，我这边暂时也不能稳定的复现，后面再看。    
主要是打不开大图这才是大问题，之前我一次都没没遇到过

**Comment by lihaoyun6** [comment]
> > <img alt="image" width="563" src="https://user-images.githubusercontent.com/16348097/235744816-86cf9b5c-479d-4564-ac55-e095b32a4b22.png">
> > 在使用路径导航器返回上层目录后, 好像脚本会错误的把某个日期文件夹当做文件去尝试打开, 导致出现此错误
> 
> 这个问题你可以忽略，除了打印错误没什么影响，我这边暂时也不能稳定的复现，后面再看。 主要是打不开全屏预览这才是大问题，之前我一次都没没遇到过

研究出一个在我这里百分百复现此bug的方法:
1. 通过快速启动打开"文生图"
2. 点击进入任何一个日期文件夹, 但不要打开任何图片
3. 使用路径导航器返回上层目录
4. 再次点击进入刚刚进入的日期文件夹
5. 这时点击文件夹中的任何图片都会触发无法打开预览的bug

**Comment by zanllp** [comment]
> > > <img alt="image" width="563" src="https://user-images.githubusercontent.com/16348097/235744816-86cf9b5c-479d-4564-ac55-e095b32a4b22.png">
> > > 在使用路径导航器返回上层目录后, 好像脚本会错误的把某个日期文件夹当做文件去尝试打开, 导致出现此错误
> > 
> > 
> > 这个问题你可以忽略，除了打印错误没什么影响，我这边暂时也不能稳定的复现，后面再看。 主要是打不开全屏预览这才是大问题，之前我一次都没没遇到过
> 
> 研究出一个在我这里百分百复现此bug的方法:
> 
>     1. 通过快速启动打开"文生图"
> 
>     2. 点击进入任何一个日期文件夹, 但不要打开任何图片
> 
>     3. 使用路径导航器返回上层目录
> 
>     4. 再次点击进入刚刚进入的日期文件夹
> 
>     5. 这时点击文件夹中的任何图片都会触发无法打开预览的bug
> 
> 
> 并且触发此bug的时候, 前端控制台会显示这种报错 <img alt="image" width="1146" src="https://user-images.githubusercontent.com/16348097/235747642-bade41c4-850f-4ce5-8a51-9d6842c89e60.png">

有点麻烦，看起来是上游库的有个bug https://github.com/Akryum/vue-virtual-scroller/pull/784 而且还不维护了，我看能不能自己fork后重新发布下

**Comment by lihaoyun6** [comment]
> 有点麻烦，看起来是依赖库的有个bug [Akryum/vue-virtual-scroller#784](https://github.com/Akryum/vue-virtual-scroller/pull/784) 而且还不维护了，我看能不能自己fork后重新发布下

好的, 那我暂时先用刷新的方法临时解决, 辛苦您了

**Comment by zanllp** [comment]
应该修好了，我试了刚才的步骤没什么问题

**Comment by lihaoyun6** [comment]
> 应该修好了，我试了刚才的步骤没什么问题

是的, 已经修复了, 我这边更新之后也正常了. 
十分感谢
