### ISSUE TITLE
Missing  __init__.py prevents proper module importing in scripts folder

### ISSUE THREAD

**Issue by axs-1553** [zanllp/sd-webui-infinite-image-browsing#765]
When installing the Infinite Image Browser extension, it fails to load due to Python's module import system not recognizing the scripts directory as a proper package.

Error Details:
*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "[...]/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      [...]
      File "[...]/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
    ModuleNotFoundError: No module named 'scripts.iib'

Root Cause:
The scripts folder is missing the required __init__.py file that Python needs to treat the directory as a package. This prevents the relative import 'from scripts.iib.api' from working correctly.

Solution:
1. Create an empty __init__.py file in the scripts folder
2. Create an empty __init__.py file in the scripts/iib folder

These files should be included in the repository by default to ensure proper Python package structure and prevent import errors during installation.

Environment:
- Stable Diffusion WebUI Forge
- Windows 10/11
- Python 3.x

**Comment by hackedhijacked-afk** [comment]
i get this issue too but after adding the empty __init__.py files in the node's root directory, i get this:

`Skip ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-webui-infinite-image-browsing module for custom nodes due to the lack of NODE_CLASS_MAPPINGS or NODES_LIST (need one).`
