### ISSUE TITLE
Exception in ASGI application while deleting an Image: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by yamanahlawat** [zanllp/sd-webui-infinite-image-browsing#97]
I encountered an exception in the ASGI application while trying to delete an Image. The traceback points to an sqlite3.OperationalError, indicating that the database is locked.

```ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/venv/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/api.py", line 68, in delete_files
    conn = DataBase.get_conn()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/db/datamodel.py", line 28, in get_conn
    conn = clz.init()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/db/datamodel.py", line 36, in init
    Floder.create_table(conn)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/diffusion/code/Users/yaman/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/db/datamodel.py", line 369, in create_table
    cur.execute(
sqlite3.OperationalError: database is locked```

**Comment by zanllp** [comment]
Are you running multiple instances of Stable-diffusion-webui or running the extension separately while Stable-diffusion-webui is already running?

**Comment by yamanahlawat** [comment]
no, I am not running multiple instances of webui.

this happens as soon as i open webui and go to image browser and try to delete any image.

**Comment by steffenr** [comment]
I'm getting the same error. I'm running a single instance of A1111 webui. 
Seems to be a DB locking problem with sqlite3. In the console, you find the error `sqlite3.OperationalError: database is locked`..

**Comment by zanllp** [comment]
> 



> I'm getting the same error. I'm running a single instance of A1111 webui. Seems to be a DB locking problem with sqlite3. In the console, you find the error `sqlite3.OperationalError: database is locked`..

Does this error occur frequently? Under what circumstances does it trigger?

**Comment by yamanahlawat** [comment]
@zanllp Yes, it happens all the time. there are no circumstances. as soon as I start Webui, go to the image browser. try deleting an image. it throws the error

**Comment by yamanahlawat** [comment]
> > 
> 
> > I'm getting the same error. I'm running a single instance of A1111 webui. Seems to be a DB locking problem with sqlite3. In the console, you find the error `sqlite3.OperationalError: database is locked`..
> 
> Does this error occur frequently? Under what circumstances does it trigger?

I'll update the extension and try it. Thanks @zanllp

**Comment by yamanahlawat** [comment]
@zanllp it didn't work. sharing a screencast. if you see in the screencast the initial load of Webui, the database gets locked. then I go to IIB and try deleting an image. it fails with the error `database is locked`


https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12144602/519d935f-65d2-4ba4-bad9-9c15c88a9dd6

**Comment by yamanahlawat** [comment]
<img width="1223" alt="image" src="https://github.com/zanllp/sd-webui-infinite-image-browsing/assets/12144602/fd4902d0-67cf-4027-b313-3958b8625408">

i have pulled the latest code.

**Comment by zanllp** [comment]
I currently can't locate where the problem is occurring. I can't reproduce this issue myself. Can you delete the iib.db and then reopen sd-webui?

**Comment by zanllp** [comment]
It seems like it has been too long since you received a reply. If you need to continue, please open a new issue or reopen this one.
